-- MySQL Script generated by MySQL Workbench
-- Sun May 31 22:22:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema anjk18
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `display_name` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `bio` TEXT NULL,
  `reputation` INT NOT NULL DEFAULT 0,
  `votes` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`display_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comment_containers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comment_containers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NOT NULL,
  `body` TEXT NOT NULL,
  `comment_container` INT NOT NULL,
  `author` INT NOT NULL,
  `rating` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_comment_containers1_idx` (`comment_container` ASC),
  INDEX `fk_questions_users1_idx` (`author` ASC),
  CONSTRAINT `fk_questions_comment_containers1`
    FOREIGN KEY (`comment_container`)
    REFERENCES `comment_containers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_users1`
    FOREIGN KEY (`author`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` INT NOT NULL,
  `body` TEXT NOT NULL,
  `comment_container` INT NOT NULL,
  `author` INT NOT NULL,
  `rating` INT NOT NULL DEFAULT 0,
  `accepted` TINYINT NOT NULL DEFAULT 0,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `question`),
  INDEX `fk_answers_questions_idx` (`question` ASC),
  INDEX `fk_answers_comment_containers1_idx` (`comment_container` ASC),
  INDEX `fk_answers_users1_idx` (`author` ASC),
  CONSTRAINT `fk_answers_questions`
    FOREIGN KEY (`question`)
    REFERENCES `questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_comment_containers1`
    FOREIGN KEY (`comment_container`)
    REFERENCES `comment_containers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_users1`
    FOREIGN KEY (`author`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment_container` INT NOT NULL,
  `author` INT NOT NULL,
  `body` TEXT NOT NULL,
  `rating` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_comment_containers1_idx` (`comment_container` ASC),
  INDEX `fk_comments_users1_idx` (`author` ASC),
  CONSTRAINT `fk_comments_comment_containers1`
    FOREIGN KEY (`comment_container`)
    REFERENCES `comment_containers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`author`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `frequency` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questions_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questions_has_tags` (
  `question` INT NOT NULL,
  `tag` INT NOT NULL,
  PRIMARY KEY (`question`, `tag`),
  INDEX `fk_questions_has_tags_tags1_idx` (`tag` ASC),
  INDEX `fk_questions_has_tags_questions1_idx` (`question` ASC),
  CONSTRAINT `fk_questions_has_tags_questions1`
    FOREIGN KEY (`question`)
    REFERENCES `questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_has_tags_tags1`
    FOREIGN KEY (`tag`)
    REFERENCES `tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
